<?php

/**
 * Magedelight
 * Copyright (C) 2016 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category Magedelight
 * @package Magedelight_Storepickup
 * @copyright Copyright (c) 2016 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$field = $this->getField();

$html = "";
if ($field['data'] != "") {
    $addressvalue = explode('\n', $field['data']);

    $html .= '<div id="address-input-cont">';
    $html .= '<input id="storelocator_address_one" name="storelocator[address][]" data-ui-id="adminhtml-storelocator-edit-tab-storetime-0-fieldset-element-text-storelocator-address" value="' . $addressvalue[0] . '" title="Address" type="text" class=" input-text admin__control-text required-entry _required"/>';
    if (count($addressvalue) > 1) {
        $html .= '<input id="storelocator_address_two" name="storelocator[address][]" data-ui-id="adminhtml-storelocator-edit-tab-storetime-0-fieldset-element-text-storelocator-address" value="' . $addressvalue[1] . '" title="Address" type="text" class=" input-text admin__control-text validate-street"/>';
    } else {
        $html .= '<input id="storelocator_address_two" name="storelocator[address][]" data-ui-id="adminhtml-storelocator-edit-tab-storetime-0-fieldset-element-text-storelocator-address" title="Address" type="text" class=" input-text admin__control-text validate-street"/>';
    }
    $html .= '</div>';
} else {
    $html .= '<input id="storelocator_address_one" name="storelocator[address][]" data-ui-id="adminhtml-storelocator-edit-tab-storetime-0-fieldset-element-text-storelocator-address" title="Address" type="text" class=" input-text admin__control-text required-entry _required"/>';
    $html .= '<input id="storelocator_address_two" name="storelocator[address][]" data-ui-id="adminhtml-storelocator-edit-tab-storetime-0-fieldset-element-text-storelocator-address" title="Address" type="text" class=" input-text admin__control-text validate-street"/>';
}
echo $html;
?>
