<?php

/**
 * Magedelight
 * Copyright (C) 2016 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category Magedelight
 * @package Magedelight_Storepickup
 * @copyright Copyright (c) 2016 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$field = $this->getField();

$state = $field['state'];
$regionId = $field['region_id'];
$countryId = $field['country_id'];

$html = "";
$html .= '<div class="admin__field-control">
            <input data-stripe="address_state" type="text" id="storelocator_region" name="storelocator[state]" value="'. $state .'"  title="State" class="required-entry admin__control-text" />
        </div>';
echo $html;
?>


<script type="text/javascript">
 require(['jquery',"prototype", "mage/adminhtml/form"], function(){
    $('storelocator_region_id').setAttribute('defaultValue', "<?php echo $regionId ?>");
    regionupdate = new regionUpdater(storelocator_country, storelocator_region, storelocator_region_id, <?php echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>);
    });

                    require([
                    'jquery',
                    'mage/template',
                    'jquery/ui',
                    'mage/translate'
                ],
                function($, mageTemplate) {
                   $( document ).ready(function() {

                        //$( '#storelocator_country' ).trigger("<?php echo $countryId ?>",'change');
                        
                         $('#edit_form').on('change', '#storelocator_country', function(event){
                            var country_value = $('#storelocator_country').val();
                                if (country_value in regionupdate.regions ) {
                                    $('.field-state').hide();
                                    $('.field-region_id_container').show();
                                }else{
                                    $('.field-state').show();
                                    $('.field-region_id_container').hide();
                                };
                            });

                         //$("#storelocator_country").trigger("change");
                    }); 

                   $(window).load(function(){
                    var country_value = "<?php echo $countryId ?>";
                        if (country_value in regionupdate.regions ) {
                            $('.field-state').hide();
                            $('.field-region_id_container').show();
                        }else{
                            $('.field-state').show();
                            $('.field-region_id_container').hide();
                        };
                   })
                   })
 </script>