
<?php
$mcOptions=  [
                 [
                    "height" => 53,
                    "url" => $this->helper('Magestore\Storepickup\Helper\Image')->getMediaUrlImage('storepickup/markerclusterer/m1.png'),
                    "width" => 53
                 ],
                 [
                    "height" => 56,
                    "url" => $this->helper('Magestore\Storepickup\Helper\Image')->getMediaUrlImage('storepickup/markerclusterer/m2.png'),
                    "width" => 56
                 ],
                 [
                    "height" => 66,
                    "url" => $this->helper('Magestore\Storepickup\Helper\Image')->getMediaUrlImage('storepickup/markerclusterer/m3.png'),
                    "width" => 66
                 ],
                 [
                    "height" => 78,
                    "url" => $this->helper('Magestore\Storepickup\Helper\Image')->getMediaUrlImage('storepickup/markerclusterer/m4.png'),
                    "width" => 78
                 ],
                 [
                    "height" => 90,
                    "url" => $this->helper('Magestore\Storepickup\Helper\Image')->getMediaUrlImage('storepickup/markerclusterer/m5.png'),
                    "width" => 90
                 ]
            ]; ?>

<div class="storepickup-wrapper col-full">
    <h2 class="title-page"><?php echo __('Store pickup') ?></h2>
    <?php echo $block->getChildHtml('storepickup.searchbox'); ?>
    <div class="boxes-content">
        <?php echo $block->getChildHtml('storepickup.mapbox'); ?>
        <?php echo $block->getChildHtml('storepickup.liststorebox'); ?>
    </div>
    <div class="overlay-bg">
        <img src="<?php echo $block->getViewFileUrl('Magestore_Storepickup::images/ajax-loader.gif') ?>" alt="overlay" />
    </div>
    <script type="text/javascript">
        var mcOptions = JSON.parse('<?php echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($mcOptions) ?>');
        var loadStoreURL = '<?php echo $block->getUrl('storepickup/index/loadstore') ?>';
        if(window.location.href.slice(0,5)=='https') loadStoreURL= loadStoreURL.replace("http:","https:");
        require(['jquery', 'magestore/googlemap', 'Magestore_Storepickup/js/makercluster'], function($){
            $(document).ready(function ($) {
                $('.googlemap').GoogleMap({
                    urlLoadStore: loadStoreURL,
                    paginationWrapper: '.pagination-wrapper',
                    liststoreContainer: '.list-store-container',
                    storePopupTemplate: '.popup-store-template',
                    listTag: '.list-tag-ul',
                    searchBox: '.search-box',
                    loader: '.overlay-bg',
                    defaultRaidus: '<?php echo $block->getSystemConfig()->getDefaultRadius() ?>',
                    distanceUnit: '<?php echo $block->getSystemConfig()->getDistanceUnit() ?>',
                    circleCenterIcon: '<?php echo $block->getViewFileUrl('Magestore_Storepickup/images/circlecenter.png') ?>',
                    mediaUrlImage: '<?php echo $block->getMediaUrlImage() ?>'
                });
            });
        });
    </script>
</div>
