# The services of the project.
#
# Each service listed will be deployed to power your project.

mysql:
    type: mysql:10.0
    disk: 5148

redis:
    type: redis:3.0

rabbitmq:
    type: rabbitmq:3.7
    disk: 1024
