<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
$ruleId = $this->getRequest()->getParam('storelocator_id');
if ($ruleId) {
?>
<div style="position: absolute; right: 0; top: 110px;">
    <button type="button" id="product_listing">PRODUCTS LISTING</button>
</div>
<div class="productnewgrid"></div>
<?php  } ?> 
<script>
    require([
        "jquery",
        "mage/mage",
        'jquery/ui', // Jquery UI Library
    ], function ($) {
//<![CDATA[
        $(document).ready(function () {
            function primaryGrid(){
                $.ajax({
                    showLoader: true,
                    url: baseUrl + 'admin/storepickupadmin/storeinfo/products/id/'+id+'/form_key/'+key,
                    data: id,
                    type: "POST",
                    success: function (data)
                    {   $('.productnewgrid').empty();
                        $('.productnewgrid').prepend('<span type="button" class="admin__collapsible-title" id="product_listing_collapsible">\n\
                        CONDITION PRODUCTS</span>\n\
                        ');
                        $('.productnewgrid').append('<div id="products-list">' + data + '</div>');
                        $("#product_listing_collapsible").click(function(){
                            $("#products-list").slideToggle( "fast" );
                        });
                    },
                    error: function (error)
                    {
                        console.log(error);
                    }
                });
            }
            
            var key = '<?php echo $block->getFormKey(); ?>';
            var id = '<?php echo $this->getRequest()->getParam('storelocator_id'); ?>';
            var baseUrl = '<?php echo $baseUrl; ?>';
            $('#product_listing').click(function () {
               primaryGrid();   
            });
        });
//]]>
    });




</script>